#!/usr/bin/env zsh
###################################################
## ╔═╗╦╦  ╔═╗           ______________________________
## ╠╣ ║║  ║╣  -NAME:    .zshrc
## ╚  ╩╩═╝╚═╝           ''''''''''''''''''''''''''''''
##   -PATH:     /share/zsh/
##   -STATUS:   work in progress
##   -USAGE:    RC-File for zsh (NixOS version)
##   -AUTHOR:   amxamxa
##   -REPO:     github.com/amxamxa/zsh
##   -OS:       NixOS 25.11  (declarative, no Flakes, no Home-Manager)
##   -SHELL:    zsh 5.9
##   -TERM:     kitty 0.37.0
## -------------------------------------------------------
## DESCRIPTION:
##   Main zsh configuration file. Handles environment variables,
##   tool initialization (zoxide, cheat, navi, micro), LS_COLORS
##   via vivid, and sources modular config files from $ZDOTDIR.
##   Uses source_or_error() for safe sourcing with validation.
##   Uses check_sources() for pre-flight existence checks.
##
## STRUCTURE:
##   1.  Early color definitions (needed before sourcing)
##   2.  Startup visual / lolcat banner
##   3.  LS_COLORS via vivid
##   4.  Tool initialization: micro, zoxide, cheat, navi
##   5.  Tetris (built-in zsh module)
##   6.  Disabled modules: mcfly, fallback prompt, pager, manpager
##   7.  Decorative separators (blahaj)
##   8.  Logging helpers (_zrc_error / _zrc_warn / _zrc_verbose)
##   9.  source_or_error() function
##   10. check_sources() + sourcing of config modules
##   11. Cosmetics / shortcuts image / shell cleanup
##
## DEPENDENCIES (runtime):
##   lolcat, vivid, micro, zoxide, cheat, navi, blahaj, chafa
##   powerlevel10k (NixOS package: zsh-powerlevel10k)
##
## NOTES:
##   - set filetype zsh
##   - All comments are intentionally preserved
##   - Commented-out blocks kept for reference / future use
##   - Color variables are defined early (Section 1) so tool-check
##     messages render correctly before aliases.zsh is sourced
##
## CHANGELOG:
##   2025-03-15: Translated all comments to English, added check_sources(),
##               simplified source file list using an array, improved
##               documentation.
###################################################


# ══════════════════════════════════════════════════════════
# 1. EARLY COLOR DEFINITIONS
#    These must come first — color variables are used by the
#    tool-check blocks (micro, zoxide, cheat, navi) which run
#    BEFORE aliases.zsh is sourced. Without this block the
#    escape sequences would produce empty strings.
#
#    FIX: If colors are already exported via environment.nix
#    or .zshenv, this block can be removed to avoid duplication.
# ══════════════════════════════════════════════════════════
RED="\033[0;31m"
GREEN="\033[0;32m"
GELB="\033[0;33m"     # yellow (German: gelb) – kept for backward compatibility
YELLOW="\033[1;33m"
PINK="\033[0;35m"
CYAN="\033[0;36m"
VIOLET="\033[0;35m"
RESET="\033[0m"


# ══════════════════════════════════════════════════════════
# 2. STARTUP BANNER
#    Animated ASCII art rendered via lolcat.
#    --animate and --duration require lolcat >= 0.11
#    The printf escape sequences draw a stylised "U / V" logo.
# ══════════════════════════════════════════════════════════
echo "  󰞷  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="aro"
echo -e " \t ______    ______ \t\t\n         / / / /   / /\ \ \ \t\t\n        / / / /   / /  \ \ \ \t\t\n        \ \ \\  / /   / / / \t\t\n         \_\_\_\/_/   /_/_/ \t\t\n" | lolcat --animate --duration 2
echo "  󰞷  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="nb"
# man eza_colors
# Codes accepted by eza: 38;5;nnn for a colour from 0 to 255
# Preview all 256 colours:
#   for i in {0..255}; do echo -e "\033[38;5;${i}m sample text in color ${i} \033[0m"; done

# To use the Meta or Alt keys, you may need to revert to single-byte mode:
#unsetopt MULTIBYTE        # Disable multi-byte character sets
#unsetopt CASEGLOB
# unsetopt HIST_SAVE_NO_DUPS  # Write duplicate events to the history file

## ZDOTDIR — override if zsh config lives outside $HOME
##export ZDOTDIR="/share/zsh/"
##export ZFUNCDIR="/share/zsh/functions"


# ══════════════════════════════════════════════════════════
# 3. LS_COLORS — generated by vivid from a custom YAML schema
#    Fallback chain: custom YAML → rose-pine-moon → alabaster_dark
#    See: https://github.com/sharkdp/vivid
# ══════════════════════════════════════════════════════════
if [[ -f "$ZDOTDIR/colors/color-schema.yml" ]]; then
    if vivid_output="$(vivid generate "$ZDOTDIR/colors/color-schema.yml" 2>/dev/null)"; then
        export LS_COLORS="$vivid_output"
    else
        # Custom schema failed — fall back to built-in rose-pine-moon theme
        export LS_COLORS="$(vivid generate rose-pine-moon)"
        printf "\t${GREEN}󰞷 .... vivid with rose-pine-moon ${RESET}\n"
    fi
else
    # Schema file not found — use alabaster_dark as last resort
    export LS_COLORS="$(vivid generate alabaster_dark)"
    printf "\t${GREEN}󰞷 .... vivid with alabaster_dark ${RESET}\n"
fi

# Already set in environment.nix — project paths
#export PRO="/home/project"
#export NIX="/share/nixos/configurationNix"
#export S="/share"
#export KITTY_CONFIG_DIRECTORY="/share/kitty"
#export GIT_CONFIG="/share/git/config"
#export EMACSDIR="/share/emacs"
#export BAT_CONFIG_FILE="/share/bat/config.toml"
#	__________________________________________
#		  __ _  (_)__________
#		 /  ' \/ / __/ __/ _ \
#	 	/_/_/_/_/\__/_/  \___/
# Micro editor configuration
if command -v micro &> /dev/null; then
    export MICRO_CONFIG_HOME="/share/micro"
    echo "\t${GREEN} micro  ... check ${RESET}\t"
    alias edit="micro"
else
    echo "\t${RED} micro is not installed. Please install it to use these features.${RESET}"
fi
# 	__________________________________________
#		__ __    .___ ___
#		 //  \\_/||  \|__
#		/_\__// \||__/|___
# Check if 'zoxide' is installed, Zoxide configuration
if command -v zoxide &>/dev/null; then
    export _ZO_ECHO=1
    export _ZO_DATA_DIR="$ZDOTDIR/zoxide"
    eval "$(zoxide init zsh)"
    alias za='zoxide add'
    alias zq='zoxide query -l'
    alias zqi='cd "$(zoxide query -i)"'
    alias zr='zoxide remove'
    echo "\t${PINK} zoxide ... check ${RESET}\t"
else
    echo "\t${RED} zoxide is not installed. Please install it to use these features.${RESET}"
    sleep 1
fi
#	----------__------------_----------------
#		 ____/ /  ___ ___ _/ /_
#		/ __/ _ \/ -_) _ `/ __/
#		\__/_//_/\__/\_,_/\__/
# Check if 'cheat' is installed, Cheat configuration
if command -v cheat &> /dev/null; then
    export CHEAT_USE_FZF="true"
    export CHEAT_CONFIG_PATH="$ZDOTDIR/cheat/conf.yaml"
    echo "\t${GREEN} cheat  ... check ${RESET}\t"
    sleep 0.1
else
    echo "\t${RED} cheat is not installed. Install it if needed to use these features.${RESET}"
    sleep 2.1
fi

# Navi configuration  # with "^g" for the widget
if command -v navi &> /dev/null; then
    echo "\t${PINK} navi  ... check ${RESET}\t"
    if [[ -z ${NAVI_CONFIG+x} ]]; then
        export NAVI_CONFIG="$ZDOTDIR/navi"
        echo "\t${GELB} NAVI_CONFIG was set to ${YELLOW}'$ZDOTDIR/navi'${GREEN}. ${RESET}"
    else
        echo "\t${PINK} NAVI_CONFIG is already set to: ${YELLOW}'$NAVI_CONFIG'${GREEN}. ${RESET}"
    fi
else
    echo "\t${RED} navi is not installed. Install it if needed to use these features.${RESET}"
    sleep 1
fi

#------------------------------------------
#     oooooo         o         o
#       8   .oPYo.  o8P oPYo. o8 .oPYo.
#       8   8oooo8   8  8  `'  8 Yb..
#       8   8.       8  8      8   'Yb.
#       8   `Yooo'   8  8      8 `YooP'
#    :..::..:::.....:::..:..:::::..:.....:
# play Tetris in Shell, press H for navigation
autoload -Uz tetriscurses
alias tetris=tetriscurses

#-------------------------------------------
# McFly for History Mgmt
 # mcfly as CTRL + R
 # -----
 #  if command -v mcfly &> /dev/null; then
 #    echo "\t${PINK} Mcfly  ... check ${RESET}\t"
 #    eval "$(mcfly init zsh)"
 #    export MCFLY_FUZZY=2 # 0 is off; Values in the 2-5 range get good results so far
 #    export MCFLY_RESULTS=50
 #    export MCFLY_DELETE_WITHOUT_CONFIRM=true
 #    export MCFLY_INTERFACE_VIEW=BOTTOM
 #    export MCFLY_RESULTS_SORT=LAST_RUN
 #    export MCFLY_PROMPT="❯❯❯"
 #  else
 #     echo "\t${RED} Mc_Fly is not installed. Please install it to use these features.${RESET}\n"
 # fi
# PROMPT: see ZFUNC
#----FALLBACK 2:------------------ZSH NATIVE PROMPT-----------------------------
#    powerlevel10k_plugin_unload
#    prompt off
#    setopt prompt_subst
#    autoload -Uz colors && colors
#    PROMPT='%F{184}%n%f@%F{013}%m%f%F{025}%K{118} in %k%f%F{225}%K{055}%~%f%k%F{063}%K{045} --> %k%f'
#    RPROMPT='|%F{#FFCA5B}ERR:%?|%F{#CF36E8}%K{#39257D}%f%k%K{#3B0045}%F{#518EA9}%D{%e.%b.}%f%k%F{#FFEAA0}%K{#1E202C}%f%k|%F{#FFEAA0}%K{#95235F}%D{%R}%f%k%F{#FFCA5B}|'
#    _log WARNING "Using minimal fallback prompt; install starship or powerlevel10k for richer prompt"


# --- Pager Configuration ---
#export PAGER="less -R"
# --RAW-CONTROL-CHARS: Show control characters (like color codes) correctly
# --chop-long-lines: 	Do not wrap lines
# --no-init: 		Do not clear the screen
# --long-prompt:  	Verbose status line
#export LESS="--long-prompt --RAW-CONTROL-CHARS --ignore-case --quit-if-one-screen --quit-on-intr --no-init --mouse --hilite-search --use-color -Dd+r -Du+b"
#
# # Manpager configuration------------------------
# export MANROFFOPT="-c"
# export MANWIDTH="60"
# if command -v bat &> /dev/null; then
#  #   export MANPAGER="bat --paging=always --style=changes -l man -p"
#    export  MANPAGER='sh -c "col -bx | bat --paging=always --style=changes -l man"'
#    echo "${GREEN} \t... bat as man-pager ... check ${RESET}\t"
# else
#     export MANPAGER="less -FRX --quit-if-one-screen --no-init"
#     echo "${GELB} less -FRX as man-pager  ... check ${RESET}"
#       # Enable color support for less via Termcap sequences
#   export LESS_TERMCAP_mb="\e[1;31m"; # Start blinking
#   export LESS_TERMCAP_md="\e[1;36m"; # Start bold (Cyan)
#   export LESS_TERMCAP_me="\e[0m";    # End bold/blink
#   export LESS_TERMCAP_so="\e[01;44;33m"; # Start standout (Yellow on Blue)
#   export LESS_TERMCAP_se="\e[0m";    # End standout
#   export LESS_TERMCAP_us="\e[1;32m"; # Start underline (Green)
#   export LESS_TERMCAP_ue="\e[0m";    # End underline
#
# fi
# echo "   󰞷 "
echo "  󰞷  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="aroace"
# ----------------------------------------------------------------------
# source_or_error() – safely source one or more files with validation.
# All messages are written to stderr (>&2) so that stdout remains clean.
#
# Return Codes
# ------------
#   2  No arguments supplied (or only empty strings)
#   3  Completed with one or more errors (validation or sourcing)
#   0  Success

#	__________________________________________________________
#   ███████╗ ██████╗ ██╗   ██╗██████╗  ██████╗███████╗
#   ██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔════╝██╔════╝
#   ███████╗██║   ██║██║   ██║██████╔╝██║     █████╗
#   ╚════██║██║   ██║██║   ██║██╔══██╗██║     ██╔══╝
#   ███████║╚██████╔╝╚██████╔╝██║  ██║╚██████╗███████╗
#   ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚══════╝
#  _______________________________________________________
# Function to source files with error handling
source_or_error() {
    local file="$1"
    local error_output
    if [[ ! -f "$file" ]]; then
        printf "\t${RED} 󰅙 nicht gefunden!${RESET}${NIGHT}${BOLD} $file ${RESET}\n" >&2
        return 1
    fi
    if error_output=$(source "$file" 2>&1); then
        source "$file"
        printf "\t${GREEN}󰞷 src pass:\t${RESET}${NIGHT}${BOLD} $file ${RESET}\n"
        return 0
    else
        printf "\t${RED} 󰅙 Fehler beim Laden!${RESET}${NIGHT} $file ${RESET}\n" >&2
        printf "\t${RED}Details: $error_output${RESET}\n" >&2
        return 1
    fi
}




  source_or_error   "$ZDOTDIR/aliases.zsh"
      source_or_error "$ZDOTDIR/functions/shortcuts.zsh"
      source_or_error "$ZDOTDIR/functions/fff.zsh"
      source_or_error "$ZDOTDIR/functions/zfunctions.zsh"
      source_or_error "$ZDOTDIR/functions/my-functions.zsh"
      source_or_error "$ZDOTDIR/functions/my-functions.sh"
      source_or_error "$ZDOTDIR/functions/cowmuh.sh"
          source_or_error "$ZDOTDIR/functions/zfunctions.zsh"
      source_or_error "$ZDOTDIR/functions/zshCopyCmdToNote.sh"
      source_or_error "/run/current-system/sw/share/zsh/themes/powerlevel10k/powerlevel10k.zsh-theme"
      source_or_error "$ZDOTDIR/prompt/p10k.zsh"


# Disabled (uncomment to activate):
# source_or_error "$ZDOTDIR/functions/batNoComment.sh"
# source_or_error "$ZDOTDIR/functions/prompt-selector.zsh"
# source_or_error "$ZDOTDIR/fzf/fzf-tools.zsh"
# source_or_error "$ZDOTDIR/fzf/fzf-mxx.zsh"
# source_or_error "$ZDOTDIR/plugins/tetris.zsh"
# source_or_error "$ZDOTDIR/functions/prompt-selector.zsh"


# source_or_error "$ZDOTDIR/fzf/fzf-tools.zsh"
# source_or_error "$ZDOTDIR/fzf/fzf-mxx.zsh"
# /share/zsh/plugins/term-theme.zsh #integrated into .zshrc!
# source_or_error "$ZDOTDIR/plugins/tetris.zsh

 	sleep 1

# =================================
echo "  󰞷  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="aroace"
# Weather display------------------------------------------
if command -v curl &> /dev/null; then
    echo -e "${BOLD}${RASPB}" && curl 'wttr.in/Dresden?m0&lang=de' && echo -e  "${RESET}"
else
    echo "\t${RED} curl is not installed. Please install it to use these features.${RESET}"
    sleep 0.2
 fi
echo "  󰞷  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="gay"
# showImg "/etc/nixos/assets/shortcuts.png" || chafa "/etc/nixos/assets/shortcuts.png"
# echo "󰞷 <><><><><><><><><><><><><><><><><><><><><><><><><><><><><> 󰞷 " | blahaj --individual --colors="gay"

# 	  Update the shell hash table
#	--------------------------------------
# ... often install or update programs, ensures your shell is always up to date
hash -r

#  COSMETICS
rm -f  "$HOME/.xsession-errors" "$HOME/.xsession-errors.old"
rm -f  "$HOME/.ICEauthority"
rm -fr "$HOME/.compose-cache"


