# config file 4 navi
# navi info config-path
# navi info cheats-path
# navi info config-example 
style:
  tag:
    color: magenta
    width_percentage: 5 # column width relative to the terminal window
    min_width: 5 # minimum column width as number of characters
  comment:
    color: dark_yellow
    width_percentage: 42
    min_width: 45
  snippet:
    color: dark_blue
    width_percentage: 55
    min_width: 45    
